export const QUERY_CLIENT_STALE_TIME = 1000 * 60 * 10 // 10 minutes
export const QUERY_CLIENT_GC_TIME = 1000 * 60 * 30 // 30 minutes

export const QUERY_CLIENT_KEYS = {
	EMPLOYEE: "EMPLOYEE",
} as const

export const QUERY_CLIENT_MUTATION_KEYS = {
	EMPLOYEE_POST: "EMPLOYEE_POST",
	EMPLOYEE_PUT: "EMPLOYEE_PUT",
	EMPLOYEE_DELETE: "EMPLOYEE_DELETE",
} as const
